#in the Command line options field/Volumes in RunConfig: -v ./test:/app1/ -v ~/Downloads:/app4/:ro
#in container: Save
FROM tomcat

#I have ${MYHOME} env variable, check that it is available for completion:
#1.
#Enter  ${MYHOME} or ${JAVA_HOME} at the Host path in the dialog
#2.
#the same is in commandline options:  -v "${JAVA_HOME}:/tmp/"