#in the Command line options field/Volumes in RunConfig: -v ./test:/app1/ -v ~/Downloads:/app4/:ro
#in container: Save
FROM tomcat

#1.
#call completion in Host path field in the dialog, should be path macroses there:
#$PROJECT_DIR$ and $USER_HOME$
#2.
#enter in the commandline: -v "$PROJECT_DIR$:/tmp/"

#I have $MYHOME$ env variable, check that it is available for completion