
#======================================================================
# Geronimo Server
# Apache Geronimo server version 2.2.1
# GERONIMO_HOME	= /apps/geronimo-tomcat6-javaee5-2.2.1/
#======================================================================
FROM jaydm/geronimo:2.2.1
ADD HelloDocker.war $GERONIMO_HOME/deploy/

