
#======================================================================
# Geronimo Server
# Apache Geronimo server version 2.2.1
# GERONIMO_HOME	= /apps/geronimo-tomcat6-javaee5-2.2.1/
#======================================================================
FROM jaydm/geronimo:2.2.1
#RUN sudo chmod +rwx $GERONIMO_HOME/deploy
#ADD helloworld.war $GERONIMO_HOME/deploy/

