
CREATE TABLE DOCKERDB.ENTITYBUS
(
    EID INT PRIMARY KEY,
    ENUMBER VARCHAR(255)
);

CREATE TABLE DOCKERDB.BUS
(
    ID INT PRIMARY KEY,
    NUMBER VARCHAR(255)
);

CREATE TABLE DOCKERDB.NAMINGSTRTEST
(
    ID INT PRIMARY KEY,
    NUMBER VARCHAR(255)
);

-- =====================================

INSERT INTO DOCKERDB.ENTITYBUS  VALUES(1,'1ENTITYBUS');
INSERT INTO DOCKERDB.ENTITYBUS VALUES(2,'2ENTITYBUS');

INSERT INTO DOCKERDB.BUS ( ID, NUMBER ) VALUES(1,'1BUS');
INSERT INTO DOCKERDB.BUS ( ID, NUMBER ) VALUES(2,'2BUS');

INSERT INTO DOCKERDB.NAMINGSTRTEST ( ID, NUMBER ) VALUES(1,'1NAMINGSTRTEST');
INSERT INTO DOCKERDB.NAMINGSTRTEST ( ID, NUMBER ) VALUES(2,'2NAMINGSTRTEST');

