
#======================================================================
# Jetty Server
# https://github.com/docker-library/docs/blob/master/jetty/tag-details.md
# JETTY_BASE = /var/lib/jetty
#======================================================================

FROM jetty
#FROM jetty:9.3.8
#FROM jetty:9.3
#FROM jetty:9
#FROM jetty:9.3.8-jre8
#FROM jetty:9.3-jre8
#FROM jetty:9-jre8
#FROM jetty:jre8
#FROM jetty:9.2.15
#FROM jetty:9.2
#FROM jetty:9.2.15-jre8
#FROM jetty:9.2-jre8
#FROM jetty:9.2.15-jre7
#FROM jetty:9.2-jre7
#FROM jetty:9-jre7
#FROM jetty:jre7

ADD HelloDocker.war $JETTY_BASE/webapps/


