
#//TODO
#======================================================================
# WebLogic Server 12.1.3 0;  port=7001, 7002 and 5556; User: weblogic  Pass: welcome1


# WebLogic Server 12.2.1

# https://hub.docker.com/r/ismaleiva90/weblogic12/
# Dockerfiles: https://github.com/oracle/docker-images/tree/master/OracleWebLogic/dockerfiles
# Default port: 7001
# Working directory=DOMAIN_HOME=/u01/oracle/weblogic/user_projects/domains/base_domain/
#
#======================================================================
#
#FROM ismaleiva90/weblogic12
#RUN mkdir -p /servers/AdminServer/upload
#run in Development Mode with -Dweblogic.ProductionModeEnabled=false
#( "Production" WLS_DISPLAY_MODE="Development")
#ADD HelloDocker.war /$DOMAIN_HOME/autodeploy/

