#======================================================================
# MySql
#======================================================================

FROM mysql
ENV MYSQL_ROOT_PASSWORD test
ENV MYSQL_DATABASE DOCKERDB

#FROM mysql:5
#FROM mysql:5.5
#FROM mysql:5.5.49
#FROM mysql:5.6
#FROM mysql:5.6.30
#FROM mysql:5.7
#FROM mysql:5.7.12

