
#======================================================================
# Resin Server 4.0.40
# JDK 8.
# https://hub.docker.com/r/expertsystems/resin/
# RESIN_HOME	/usr/local/share/resin-4.0.40
# WAR files go in the /var/resin/webapps
#======================================================================

FROM expertsystems/resin
EXPOSE 8080
ADD helloworld.war /var/resin/webapps


